import { Scheme } from '../types';

export const MOCK_SCHEMES: Scheme[] = [
  {
    id: 'pm-kisan',
    title: 'PM-KISAN (Pradhan Mantri Kisan Samman Nidhi)',
    nativeTitle: {
      en: 'PM-KISAN (Farmer Income Support)',
      hi: 'पीएम-किसान (किसान सम्मान निधि)',
      ta: 'பிஎம்-கிசான் (விவசாயி வருமான உதவி)',
      te: 'పిఎం-కిసాన్ (రైతు ఆదాయ సహాయం)',
      bn: 'পিএম-কিষাণ (কৃষক সম্মান নিধি)',
      mr: 'पीएम-किसान (शेतकरी सन्मान निधी)',
      gu: 'પીએમ-કિસાન (ખેડૂત સહાય)',
    },
    category: 'Agriculture',
    department: 'Ministry of Agriculture & Farmers Welfare',
    summary: 'Direct income support of ₹6,000 per year in three equal installments to eligible landholding farmer families across India.',
    fullDescription: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN) provides financial support to small and marginal farmer families to procure agricultural inputs such as seeds, fertilizers, and equipment. The amount is directly credited to the bank accounts of farmers through Direct Benefit Transfer (DBT).',
    eligibilityCriteria: {
      occupations: ['Farmer'],
      allowedCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
      maxIncome: '5 Lakhs',
    },
    benefits: [
      '₹6,000 per annum distributed in 3 equal quarterly installments of ₹2,000',
      'Direct Benefit Transfer (DBT) straight to Aadhaar-linked bank account',
      'No middleman commission or procedural delay',
    ],
    documentsRequired: [
      'Aadhaar Card of Landholder',
      'Landholding Ownership Record (Khasra/Khatauni / RoR)',
      'Aadhaar-seeded Active Savings Bank Account Passbook',
      'Active Mobile Number for OTP Verification',
    ],
    deadline: '2026-08-31',
    applicationSteps: [
      'Step 1: Visit the official PM-KISAN portal or your nearest Common Service Centre (CSC).',
      'Step 2: Enter Aadhaar number and select your State, District, and Sub-District.',
      'Step 3: Upload your land ownership certificate and bank passbook scan.',
      'Step 4: Submit e-KYC using Aadhaar OTP verification.',
      'Step 5: Track application status using your Aadhaar or Mobile number.',
    ],
    officialUrl: 'https://pmkisan.gov.in',
    sourceVerifiedDate: '2026-07-20',
    isUrgent: true,
    iconName: 'Sprout',
    popularityScore: 98,
  },
  {
    id: 'ayushman-bharat',
    title: 'Ayushman Bharat - PM Jan Arogya Yojana (PM-JAY)',
    nativeTitle: {
      en: 'Ayushman Bharat (Health Insurance)',
      hi: 'आयुष्मान भारत (स्वास्थ्य बीमा)',
      ta: 'ஆயுஷ்மான் பாரத் (சுகாதார காப்பீடு)',
      te: 'ఆయుష్మాన్ భారత్ (ఆరోగ్య భీమా)',
      bn: 'আয়ুষ্মান ভারত (স্বাস্থ্য বীমা)',
      mr: 'आयुष्मान भारत (आरोग्य विमा)',
      gu: 'આયુષ્માન ભારત (આરોગ્ય વીમો)',
    },
    category: 'Healthcare',
    department: 'National Health Authority (NHA)',
    summary: 'Free health coverage up to ₹5 Lakhs per family per year for secondary and tertiary care hospitalization.',
    fullDescription: 'Ayushman Bharat PM-JAY is the world’s largest government-funded healthcare scheme, offering cashless access to secondary and tertiary healthcare services for vulnerable and low-income families identified in SECC data.',
    eligibilityCriteria: {
      maxIncome: '2.5 Lakhs',
      allowedCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    },
    benefits: [
      'Cashless hospital treatment up to ₹5,00,000 per family per year',
      'Covers 1,900+ medical procedures, surgeries, and critical care treatments',
      'Includes pre-hospitalization (3 days) and post-hospitalization (15 days) expenses',
      'Valid across 27,000+ empanelled government and private hospitals nationwide',
    ],
    documentsRequired: [
      'Aadhaar Card or Ration Card',
      'Ration Card / SECC Household ID Verification',
      'Mobile Number',
    ],
    deadline: 'Ongoing Open Scheme',
    applicationSteps: [
      'Step 1: Check eligibility on beneficiary.nha.gov.in using Aadhaar or Ration Card.',
      'Step 2: Visit any empanelled hospital or CSC with your Aadhaar and Ration Card.',
      'Step 3: Complete biometric/OTP authentication with Ayushman Mitra.',
      'Step 4: Download your Ayushman PVC Card instantly upon approval.',
    ],
    officialUrl: 'https://pmjay.gov.in',
    sourceVerifiedDate: '2026-07-22',
    isUrgent: false,
    iconName: 'HeartPulse',
    popularityScore: 95,
  },
  {
    id: 'pm-awas-yojana',
    title: 'Pradhan Mantri Awas Yojana (PMAY-Urban & Gramin)',
    nativeTitle: {
      en: 'PM Awas Yojana (Housing Support)',
      hi: 'पीएम आवास योजना (आवास सहायता)',
      ta: 'பிஎம் ஆவாஸ் யோஜனா (வீட்டு உதவி)',
      te: 'పిఎం ఆవాస్ యోజన (గృహ సహాయం)',
      bn: 'পিএম আবাসন যোজনা (গৃহ নির্মাণ)',
      mr: 'पीएम आवास योजना (घरकुल योजना)',
      gu: 'પીએમ આવાસ યોજના (મકાન સહાય)',
    },
    category: 'Housing',
    department: 'Ministry of Housing and Urban Affairs',
    summary: 'Financial subsidy up to ₹2.67 Lakhs for constructing or buying a pucca house for low-income and rural families.',
    fullDescription: 'PMAY aims to ensure all eligible urban and rural households have access to a pucca house equipped with basic amenities like water, sanitation, and electricity.',
    eligibilityCriteria: {
      maxIncome: '5 Lakhs',
      allowedCategories: ['General', 'OBC', 'SC', 'ST', 'EWS'],
    },
    benefits: [
      'Credit Linked Subsidy up to ₹2,67,000 on home loan interest',
      'Financial assistance of ₹1.20 Lakhs in plains and ₹1.30 Lakhs in hilly states for rural house construction',
      'Direct transfer to house owner’s bank account in construction milestones',
    ],
    documentsRequired: [
      'Aadhaar Card of Applicant and Family Members',
      'Income Certificate issued by Revenue Authority',
      'Land Ownership Record or Allotment Letter',
      'Bank Account Passbook with IFSC code',
    ],
    deadline: '2026-12-31',
    applicationSteps: [
      'Step 1: Access pmaymis.gov.in or pmayg.nic.in depending on Urban/Gramin status.',
      'Step 2: Enter Aadhaar number to open the registration form.',
      'Step 3: Fill personal, income, and bank account details accurately.',
      'Step 4: Upload photograph and land/house document scans.',
      'Step 5: Submit form and keep application reference number for tracking.',
    ],
    officialUrl: 'https://pmaymis.gov.in',
    sourceVerifiedDate: '2026-07-15',
    isUrgent: true,
    iconName: 'Home',
    popularityScore: 91,
  },
  {
    id: 'e-shram',
    title: 'e-SHRAM Card Scheme (Unorganized Workers Registry)',
    nativeTitle: {
      en: 'e-SHRAM Card (Worker Social Security)',
      hi: 'ई-श्रम कार्ड (असंगठित श्रमिक सुरक्षा)',
      ta: 'இ-ஷ்ரம் கார்டு (தொழிலாளர் பாதுகாப்பு)',
      te: 'ఈ-శ్రమ్ కార్డ్ (అసంఘటిత కార్మికుల భద్రత)',
      bn: 'ই-শ্রম কার্ড (শ্রমিক সামাজিক সুরক্ষা)',
      mr: 'ई-श्रम कार्ड (असंघटित कामगार सुरक्षा)',
      gu: 'ઈ-શ્રમ કાર્ડ (શ્રમિક સુરક્ષા)',
    },
    category: 'Employment & Labor',
    department: 'Ministry of Labour and Employment',
    summary: 'Universal social security identification card and ₹2 Lakh accident insurance coverage for unorganized sector workers.',
    fullDescription: 'e-SHRAM creates a comprehensive national database of unorganized workers including construction workers, migrant workers, street vendors, domestic workers, and agricultural laborers.',
    eligibilityCriteria: {
      minAge: 16,
      maxAge: 59,
      occupations: ['Laborer', 'Farmer', 'Self-Employed', 'Unemployed'],
    },
    benefits: [
      'Accidental Death / Permanent Disability coverage of ₹2,00,000 under PMSBY',
      'Partial disability cover of ₹1,00,000',
      'Unique 12-digit UAN Card valid across all Indian states',
      'Direct eligibility for government emergency relief funds',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Active Mobile Number linked with Aadhaar',
      'Savings Bank Account details',
    ],
    deadline: 'Ongoing Open Scheme',
    applicationSteps: [
      'Step 1: Go to eshram.gov.in and click "Register on e-SHRAM".',
      'Step 2: Authenticate via Aadhaar OTP.',
      'Step 3: Enter educational, skill, occupation, and bank details.',
      'Step 4: Preview and confirm details.',
      'Step 5: Download and print your UAN e-SHRAM Card.',
    ],
    officialUrl: 'https://eshram.gov.in',
    sourceVerifiedDate: '2026-07-18',
    isUrgent: false,
    iconName: 'HardHat',
    popularityScore: 89,
  },
  {
    id: 'sukanya-samriddhi',
    title: 'Sukanya Samriddhi Yojana (Girl Child Savings)',
    nativeTitle: {
      en: 'Sukanya Samriddhi (Girl Child Savings)',
      hi: 'सुकन्या समृद्धि योजना (बेटी बचत योजना)',
      ta: 'சுகன்யா சம்ரிதி (பெண் குழந்தை சேமிப்பு)',
      te: 'సుకన్య సమృద్ధి యోజన (బాలికల పొదుపు)',
      bn: 'সুকন্যা সমৃদ্ধি যোজনা (কন্যা সন্তান সঞ্চয়)',
      mr: 'सुकन्या समृद्धी योजना (मुलींची बचत)',
      gu: 'સુકન્યા સમૃદ્ધિ યોજના (દીકરી બચત)',
    },
    category: 'Women & Child Development',
    department: 'Department of Posts / Ministry of Finance',
    summary: 'High-interest small deposit scheme for girl children offering 8.2% annual interest and tax deduction under Section 80C.',
    fullDescription: 'A government-backed savings initiative encouraging parents to build a fund for the higher education and marriage of female children up to 10 years of age.',
    eligibilityCriteria: {
      maxAge: 10,
      genderTarget: ['Female'],
    },
    benefits: [
      'High government interest rate (currently 8.2% per annum compounding annually)',
      'Tax deduction benefit under Section 80C up to ₹1,50,000 per year',
      'Partial withdrawal up to 50% allowed when girl turns 18 for higher education',
      'Full maturity after 21 years from account opening',
    ],
    documentsRequired: [
      'Birth Certificate of Girl Child',
      'Identity Proof (Aadhaar/PAN) of Parent/Guardian',
      'Address Proof of Guardian',
      'Passport size photos of child and guardian',
    ],
    deadline: 'Ongoing Open Scheme',
    applicationSteps: [
      'Step 1: Visit any Post Office branch or authorized commercial bank.',
      'Step 2: Obtain and fill out the SSY Account Opening Form.',
      'Step 3: Attach birth certificate copy and guardian ID proofs.',
      'Step 4: Deposit initial amount (Minimum ₹250).',
      'Step 5: Collect passbook.',
    ],
    officialUrl: 'https://www.indiapost.gov.in',
    sourceVerifiedDate: '2026-07-10',
    isUrgent: false,
    iconName: 'PiggyBank',
    popularityScore: 88,
  },
  {
    id: 'nsp-post-matric',
    title: 'National Scholarship Portal (NSP) Post-Matric Scholarship',
    nativeTitle: {
      en: 'NSP Scholarship (Student Aid)',
      hi: 'एनएसपी छात्रवृत्ति (छात्र सहायता)',
      ta: 'என்எஸ்பி கல்வி உதவித்தொகை',
      te: 'ఎన్‌ఎస్‌పి స్కాలర్‌షిప్ (విద్యార్థి సహాయం)',
      bn: 'এনএসপি স্কলারশিপ (ছাত্র সহায়তা)',
      mr: 'एनएसपी शिष्यवृत्ती (विद्यार्थी मदत)',
      gu: 'એનએસપી શિષ્યવૃત્તિ (વિદ્યાર્થી સહાય)',
    },
    category: 'Education',
    department: 'Ministry of Social Justice and Empowerment',
    summary: 'Tuition fee reimbursement and monthly maintenance allowance for SC/ST/OBC/EWS students pursuing Class 11 to Higher Education.',
    fullDescription: 'Provides financial support to minority and low-income students to enable them to complete post-secondary education and reduce drop-out rates.',
    eligibilityCriteria: {
      occupations: ['Student'],
      maxIncome: '2.5 Lakhs',
      allowedCategories: ['SC', 'ST', 'OBC', 'EWS'],
    },
    benefits: [
      '100% Non-refundable tuition and fee reimbursement',
      'Monthly maintenance allowance ranging from ₹550 to ₹1,200',
      'Special disability allowance for differently-abled scholars',
    ],
    documentsRequired: [
      'Aadhaar Card of Student',
      'Latest Marksheet / Passing Certificate',
      'Valid Caste Certificate issued by Competent Authority',
      'Income Certificate issued by Tehsildar/Revenue Officer',
      'Fee Receipt and Bonafide Certificate from School/College',
    ],
    deadline: '2026-10-31',
    applicationSteps: [
      'Step 1: Register on scholarship.gov.in using OTR (One-Time Registration) with Aadhaar.',
      'Step 2: Select "Post-Matric Scholarship" under your target scheme.',
      'Step 3: Fill academic details, institute name, roll number, and fee structure.',
      'Step 4: Upload scanned certificates and bonafide receipt.',
      'Step 5: Submit application to your institute for online verification.',
    ],
    officialUrl: 'https://scholarships.gov.in',
    sourceVerifiedDate: '2026-07-14',
    isUrgent: true,
    iconName: 'GraduationCap',
    popularityScore: 94,
  },
  {
    id: 'mgnrega',
    title: 'MGNREGA (100 Days Guaranteed Rural Employment)',
    nativeTitle: {
      en: 'MGNREGA (Guaranteed Rural Work)',
      hi: 'मनरेगा (100 दिन का ग्रामीण रोजगार)',
      ta: 'மகாத்மா காந்தி ஊரக வேலை உறுதித் திட்டம்',
      te: 'ఉపాధి హామీ పథకం (MGNREGA)',
      bn: 'একশ দিনের কাজ (মনরেগা)',
      mr: 'मनरेगा (ग्रामीण रोजगार हमी योजना)',
      gu: 'મનરેગા (૧૦૦ દિવસની રોજગારી)',
    },
    category: 'Employment & Labor',
    department: 'Ministry of Rural Development',
    summary: 'Guarantees 100 days of wage employment per financial year to rural households willing to do manual unskilled work.',
    fullDescription: 'Mahatma Gandhi National Rural Employment Guarantee Act enhances livelihood security in rural areas by providing guaranteed wage work for public works like water conservation, road building, and afforestation.',
    eligibilityCriteria: {
      minAge: 18,
      occupations: ['Laborer', 'Farmer', 'Unemployed'],
    },
    benefits: [
      'Guaranteed 100 days of work per year per household',
      'Daily wage paid directly into Aadhaar-linked bank account within 15 days',
      'Unemployment allowance paid if work is not provided within 15 days of applying',
      'Equal wages for men and women',
    ],
    documentsRequired: [
      'Aadhaar Card',
      'Job Card (or application for Job Card with Gram Panchayat)',
      'Bank Account Details with IFSC',
    ],
    deadline: 'Ongoing Open Scheme',
    applicationSteps: [
      'Step 1: Submit written application for Job Card to your Gram Panchayat.',
      'Step 2: Verify Aadhaar details with Gram Rozgar Sahayak.',
      'Step 3: Receive MGNREGA Job Card within 15 days.',
      'Step 4: Submit work demand request at Panchayat office to receive work allotment.',
    ],
    officialUrl: 'https://nrega.nic.in',
    sourceVerifiedDate: '2026-07-19',
    isUrgent: false,
    iconName: 'Briefcase',
    popularityScore: 92,
  },
  {
    id: 'pm-mudra',
    title: 'PM Mudra Yojana (Micro-Business Loans)',
    nativeTitle: {
      en: 'PM Mudra Yojana (Business Loans)',
      hi: 'पीएम मुद्रा योजना (व्यापार ऋण)',
      ta: 'பிஎம் முத்ரா திட்டம் (சிறு தொழில் கடன்)',
      te: 'పిఎం ముద్రా యోజన (వ్యాపార రుణాలు)',
      bn: 'পিএম মুদ্রা যোজনা (ব্যবসা ঋণ)',
      mr: 'पीएम मुद्रा योजना (व्यवसाय कर्ज)',
      gu: 'પીએમ મુદ્રા યોજના (બિઝનેસ લોન)',
    },
    category: 'Finance & Enterprise',
    department: 'Department of Financial Services',
    summary: 'Collateral-free business loans up to ₹10 Lakhs under Shishu, Kishore, and Tarun categories for non-corporate micro enterprises.',
    fullDescription: 'Provides funding to small enterprise owners, shopkeepers, artisans, fruit vendors, and micro-manufacturers to launch or expand their micro businesses without bank collateral.',
    eligibilityCriteria: {
      minAge: 18,
      occupations: ['Self-Employed', 'Laborer', 'Unemployed'],
    },
    benefits: [
      'Zero collateral or third-party guarantee required',
      'Shishu category: Loans up to ₹50,000',
      'Kishore category: Loans from ₹50,000 to ₹5 Lakhs',
      'Tarun category: Loans from ₹5 Lakhs to ₹10 Lakhs',
      'Mudra Card provided for working capital ATM cash withdrawals',
    ],
    documentsRequired: [
      'Aadhaar Card & PAN Card',
      'Proof of Business Address / GST Registration (if applicable)',
      'Quotations for machinery/inventory to be purchased',
      '6-month Bank Account Statement',
    ],
    deadline: 'Ongoing Open Scheme',
    applicationSteps: [
      'Step 1: Visit udyamimitra.in portal or any commercial/Gramin bank branch.',
      'Step 2: Download Mudra Loan Application Form corresponding to your loan category.',
      'Step 3: Attach business profile, machine quotation, and identity proofs.',
      'Step 4: Submit to bank manager for verification.',
      'Step 5: Loan amount disbursed directly upon sanction.',
    ],
    officialUrl: 'https://www.mudra.org.in',
    sourceVerifiedDate: '2026-07-12',
    isUrgent: false,
    iconName: 'Coins',
    popularityScore: 86,
  },
];
